id: I8A721F99
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T03:00:13+00:00'
last_modified: '2022-06-07T21:51:45.138940+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29572
  title: ཀླུ་སྒྲུབ་དགོངས་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C559:
      image_group_id: I5521
      title: ''
      total_pages: 148
      order: 1
      base_file: C559.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
