id: P004307
initial_creation_type: ocr
source_metadata:
  id: bdr:W29572
  title: ཀླུ་སྒྲུབ་དགོངས་རྒྱན
  author: ''
  volumes:
    1a97dcac57e34e0fb344d9b5980506d9:
      image_group_id: I5521
      title: ''
      volume_number: 1
      total_pages: 148
      base_file: v001.txt
